### ISSUE TITLE
[Feature] Alternative to "auth" for requiring bearer token

### ISSUE THREAD

**Issue by skhilliard** [Thream/socketio-jwt#232] opened 2021-10-04 17:43 UTC
## Description

Currently, if you require a bearer token thusly in your server...

```
// Require Bearer Token
const socket = io('http://localhost:9000', {
  auth: { token: `Bearer ${yourJWT}` }
})
```

The only way you can be authorized is to connect with a client something like this...

```
        this.io = io(`${socketioAddress}`, <SocketIOClient.ConnectOpts>{
            perMessageDeflate: false,
            transports: ['websocket'],
            upgrade: false,
            auth: { token: `Bearer ${this.tSessionService.token}` }
        });
```

However, some web socket clients (like WebSocket4Net for C#) don't have support for this.

## Describe the solution you'd like

Would it be possible to also support including the bearer token in a header as well?  Something in authorize.js pehaps...

```
const authorize = (options) => {
    const { secret, algorithms = ['HS256'], onAuthentication } = options;
    return async (socket, next) => {
        let encodedToken = null;
        const { token } = socket.handshake.auth;
        const { authentication } = socket.handshake.headers;
        const authenticationToken = token || authentication;
        if (authenticationToken != null) {
            const tokenSplitted = authenticationToken.split(' ');
            if (tokenSplitted.length !== 2 || tokenSplitted[0] !== 'Bearer') {
                return next(new UnauthorizedError_1.UnauthorizedError('credentials_bad_format', {
                    message: 'Format is Authorization: Bearer [token]'
                }));
```

**Comment by Divlo** [comment] 2022-02-18 16:28
Hey! :wave: @skhilliard 
Thanks for your report!
Excuse me for taking that long to respond, don't hesitate to ping me, if it feels like I don't respond to the issue, I maybe didn't see it or forgot it.

It is by design that we don't support multiple ways to pass the Bearer token, it is to ease the usage of the library, and to only have one easy working way to use it.
But this one only way to pass the token might indeed change, but that would be a **BREAKING CHANGE**.

Closing, as we can continue the discussion about that in #37.

**Closed by Divlo** 2022-02-18 16:28 UTC
Labels: feature request
